services:
  - type: web
    name: vois-scanner
    env: python
    buildCommand: "python -m pip install --upgrade pip && python -m pip install -r requirements.txt"
    startCommand: "python -m uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
